"""add pattern creation

Revision ID: 002efb4c8a18
Revises: cf7aadadfb91
Create Date: 2025-04-14 14:29:43.413174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '002efb4c8a18'
down_revision: Union[str, None] = 'cf7aadadfb91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('pattern_url', sa.String(), nullable=True),
    sa.Column('for_who', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('fabric', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('fabric_amount', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('pattern_a0_file_id', sa.Uuid(), nullable=True),
    sa.Column('pattern_a0_sa_file_id', sa.Uuid(), nullable=True),
    sa.Column('pattern_a0_sa_projector_file_id', sa.Uuid(), nullable=True),
    sa.Column('pattern_a0_projector_file_id', sa.Uuid(), nullable=True),
    sa.Column('pattern_a4_file_id', sa.Uuid(), nullable=True),
    sa.Column('pattern_instructables_file_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pattern')
    # ### end Alembic commands ###
