"""add file a4 only sa

Revision ID: 6843f91d89fc
Revises: 002efb4c8a18
Create Date: 2025-04-14 14:35:15.997864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6843f91d89fc'
down_revision: Union[str, None] = '002efb4c8a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pattern', sa.Column('pattern_a4_sa_file_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pattern', 'pattern_a4_sa_file_id')
    # ### end Alembic commands ###
