name: Build and Push Docker Image on Release

on:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract release version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MINOR_VERSION=$(echo $VERSION | cut -d '.' -f1,2)" >> $GITHUB_ENV

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            jpizquierdo/patternland-backend:${{ env.VERSION }}
            jpizquierdo/patternland-backend:${{ env.MINOR_VERSION }}
            jpizquierdo/patternland-backend:latest
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            jpizquierdo/patternland-frontend:${{ env.VERSION }}
            jpizquierdo/patternland-frontend:${{ env.MINOR_VERSION }}
            jpizquierdo/patternland-frontend:latest
